### PR TITLE
fix: update 'Data Stories' section on home pages

### LINKED ISSUE #221: Update 'Data Stories' section on home page
Our latest featured data stories on our home page are now 4 months old.  Would be great to get some of the new and prominent ones on there. I recommend these 3:

Policing in the Pandemic
by Xristos Katsaros
Link: https://medium.com/qri-io/policing-in-the-pandemic-45448687714b

Four Simple Steps to Improve U.S. Census Data CSVs
by Chris Whong
Link: https://medium.com/qri-io/four-simple-steps-to-improve-u-s-census-data-csvs-b7358ee1b18

Taming the MTA’s Unruly Turnstile Data
by Chris Whong
Link: https://medium.com/qri-io/taming-the-mtas-unruly-turnstile-data-c945f5f96ba0

### PR DESCRIPTION
**Pull request by feep**
update data stories
use curly apostrophes

closes #221

### CODE REVIEW

**Comment by feep** [comment]
@chriswhong, I have rico on review.

But I have no idea what `fireEvent('blog-card-click'` is.

I assumed it is analytics event. I gave it a useful name for the new stories I linked.

Is that correct?

Need your ok or info on `'blog-card-click'` before I merge.

**Comment by feep** [comment]
@rgardaphe, just take a look at the [diff](https://github.com/qri-io/website/pull/222/commits/a78ff498e9f5e82a653be3494e7b3519697112db) to see what changed.

And a look and some clicks in the [netlify preview](https://deploy-preview-222--qri-website.netlify.app/) to see if it works right.

For future reviews, you can find the netlify preview in the bottom details link under `All checks have passed`, `Deploy preview ready!`.

**Comment by rgardaphe** [comment]
This looks perfect. It looks good from my end. Did you want @chriswhong to weigh in before I merge?

**Comment by rgardaphe** [comment]
Ack, sorry. I just noticed the image/card on the middle story is wrong. Image is from the bike story.

Screen Shot 2020-07-17 at 11 47 37 AM

**Comment by feep** [comment]
Thanks for catching @rgardaphe. Preview is... slow.

OK, preview is up, should be fixed.

**Pull request merged**
